name: changelog

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone Codex
        env:
          PAT: ${{ secrets.GH_FRONT_CODEX_PAT }}  # Personal Access Token with repo scope
        run: |
          git clone https://x-access-token:${PAT}@github.com/Akad-Seguros/front-codex.git .codex
          source .codex/bin/start.sh

      - name: Generate changelog
        env:
          ANTHROPIC_API_KEY: ${{ secrets.CODIUM_PR_AGENT_KEY }}
          PYTHONPATH: .codex
        run: python -m pkg.changelog

      - name: Update release with changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }}" \
            | jq -r .id)
          
          body=$(cat .tmp/changelog.md)
          
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$release_id" \
            -d "{\"body\": $(echo "$body" | jq -Rs .)}"

      - name: Upload changelog artifacts
        uses: actions/upload-artifact@v4
        with:
          name: changelog-artifacts
          path: |
            .tmp/
            .aider.chat.history.md
          include-hidden-files: true
